Add a missing dep: controller_manager
Error:
```
root@7a331036e3c7:~/catkin_ws# roslaunch osrf_gear sample_environment.launch
:
ERROR: cannot launch node of type [controller_manager/controller_manager]: controller_manager
```

Code ref: robot_state_publisher is in use.
```
n130s@130s-p50:~/link/ROS/kinetic/cws_ariac/src/osrf/ariac/osrf_gear$ ack-grep -i controller_manager .
vendor/ur_gazebo/launch/controller_utils.launch
17:  <node name="joint_state_controller_spawner" pkg="controller_manager" type="controller_manager"

launch/ur10/ur10.xml
39:  <node name="arm_controller_spawner" pkg="controller_manager" type="controller_manager"
```