Add a missing dep: robot_state_publisher
Error:
```
root@7a331036e3c7:~/catkin_ws# roslaunch osrf_gear sample_environment.launch
:
ERROR: cannot launch node of type [robot_state_publisher/robot_state_publisher]: robot_state_publisher
```

Code ref: robot_state_publisher is in use.
```
$ git log -1
commit 1f8fbb6b790e4b2d8ca67bdfd65ab6c1398c65ed
Merge: ee55ce7 8709d8a
Author: Shane Loretz <sloretz@osrfoundation.org>
Date:   Fri Apr 5 22:50:38 2019 +0000

    Merged in bump_ariac_3.0.3 (pull request #134)

    Bump 3.0.2 -> 3.0.3

$ ack-grep -i robot_state_publisher .
osrf/ariac/osrf_gear/vendor/ur_gazebo/launch/controller_utils.launch
5:  <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">

osrf/ariac/osrf_gear/launch/gear.launch.template
38:  <node pkg="robot_state_publisher" type="robot_state_publisher" name="sensors_tf_publisher">
```